name: Deploy Docs

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install docs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs]

      - name: Build documentation with Sphinx
        run: |
          sphinx-build -b html docs docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: gh-pages