name: Test package
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
      - name: Lint docstrings with pydocstyle
        run: |
          pydocstyle ./src
      - name: Lint with flake8p
        run: |
          flake8p ./src
      - name: Test with pytest
        run: |
          pytest --cov ./src